language: rust
rust:
- nightly
cache: cargo

script:
- cargo build --verbose
- cargo test --verbose
- cargo clippy --verbose

before_deploy:
- cargo build --release
- mkdir sokoban
- cp -a assets target/sokoban/sokoban sokoban/

deploy:
  provider: releases
  api_key:
    secure: AXpA3BN6EEaQeaO/2ZJvhpQ9Im8G8LpXtfwHHpuL2hOOT3PIeLn+m4QI0peTqRwbh20gwtX13vjAau5iDArcPO+fY29A15vhgEImTD7/Ib5i2X+AIVL4AKod0+BUewycynmCgLtrmG4v6HSNj/KnKx1JdQFi95tfk3unzYXoToYcFVfc92sBv85hy78LGZw4eEMVLHJ7lWhDFPNDpoG1WJqLEsLsK8kcZQw4TnlNXr9FhK9VkG8eor2UsTODgcLMBO0Kh8NQhFhmmrm507wOZZyZIH0ahqTFlWv+/CrnnfFLLOBU9ib6ESd1fnvfnpbTCphgUsFsnFLgYfdPUdk3OVYCDkp2ZbHm2q5CfQw6xbdumfElEEH7r8CAJhdy2Y4VRv6S+gIqKr2wDYBxc+AnyO82Lq+w7D7+jGOPdeHSj3CAnjbewnPD6kAwna4/9ftW9vKDFDpIFPwuT07G30GNzHBNhISy8wIyCnAlSQtOYuZqhZQya7NaUzNOlITe5C02o7noRAmYFOAVRfdbAGssFHYJ965DdjaedP0MPPsNj1HyJt3R6jHVJLcn0N9r34TD1XsW7/Jg/Z+vBFHb2klgebY389SIlPm1m0qclAhtotKAHhSRoUQxJAx2x5o2hLMim8IIhYTTX7CPYGFJ0BhE/KoUCP1fUnkcrokUQ8mI7Hk=
  file_glob: true
  file: sokoban/**/*
  skip_cleanup: true
  on:
    tags: true
