[package]
authors = ["Colin Benner <colin@yzhs.de>"]
name = "sokoban"
version = "0.4.0"

[[bin]]
doc = false
name = "sokoban"
test = false

[dependencies]
ansi_term = "0.9.0"
app_dirs = "1.1.1"
clap = "2.24.2"
colog = "0.1.1"
find_folder = "0.3.0"
glium = "0.16.0"
glium_text_rusttype = "*"
image = "0.13.0"
lazy_static = "0.2.8"
log = "0.3.7"
natord = "1.0.9"
serde = "1.0.7"
serde_derive = "1.0.7"
serde_json = "1.0.2"
xml-rs = "0.6.0"

[lib]
name = "sokoban_backend"
