[package]
authors = ["Colin Benner <colin@yzhs.de>"]
name = "sokoban"
version = "0.5.0"

[[bin]]
doc = false
name = "sokoban"
test = false

[dependencies]
ansi_term = "0.11"
app_dirs = "1.2"
clap = "2.31"
colog = "0.1.1"
find_folder = "0.3.0"
glium = "0.17"
glium_text_rusttype = "0.2"
image = "0.18"
lazy_static = "1.0"
log = "0.4"
natord = "1.0"
quickcheck = "0.6"
quickcheck_macros = "0.6"
quick-xml = "0.10"
rmp-serde = "0.13"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

[lib]
name = "sokoban_backend"
