[package]
authors = ["Colin Benner <colin@yzhs.de>"]
name = "sokoban"
version = "0.4.0"

[[bin]]
doc = false
name = "sokoban"
test = false

[dependencies]
app_dirs = "1.1.1"
clap = "2.24.2"
colog = "0.1.1"
find_folder = "0.3.0"
glium = "0.16.0"
glium_text = "0.11.0"
image = "0.13.0"
lazy_static = "0.2.8"
log = "0.3.7"
serde = "1.0.7"
serde_derive = "1.0.7"
serde_json = "1.0.2"

[lib]
name = "sokoban_backend"
