[package]
authors = ["Colin Benner <colin@yzhs.de>"]
name = "sokoban"
version = "0.2.0"

[[bin]]
doc = false
name = "sokoban"
test = false

[dependencies]
colog = "0.1.1"
find_folder = "0.3.0"
gfx_core = "0.7.0"
gfx_device_gl = "0.14.0"
lazy_static = "0.2.8"
log = "0.3.7"
piston = "0.32.0"
piston2d-gfx_graphics = "0.39.0"
piston2d-graphics = "0.21.1"
piston2d-sprite = "0.36.0"
piston_window = "0.65.0"
serde = "1.0.7"
serde_derive = "1.0.7"
serde_json = "1.0.2"
uuid = "0.1.18"
xdg = "2.1.0"

[lib]
name = "sokoban_backend"
