[package]
authors = ["Colin Benner <colin@yzhs.de>"]
name = "sokoban"
version = "0.5.1"

[[bin]]
doc = false
name = "sokoban"
test = false

[dependencies]
ansi_term = "0.11"
app_dirs = "1.2"
clap = "2.32"
colog = "0.1"
failure = "0.1"
find_folder = "0.3"
glium = "0.22"
glium_text = "0.13"
image = "0.19"
lazy_static = "1.1"
log = "0.4"
natord = "1.0"
quick-xml = "0.12"
serde = "1.0"
serde_cbor = "0.9"
serde_derive = "1.0"
serde_json = "1.0"

[dev-dependencies]
quickcheck = "0.7"
quickcheck_macros = "0.7"
rand = "0.5"

[features]
cargo-clippy = []
default = []

[lib]
name = "sokoban_backend"
